ts/env/docker migration
Mikibot/yagami pull request #1
Opened 2019-07-11 17:46 UTC by Niputi

- [✔] typescript
- [❌] env file
- [❌] docker
- [❌] tested

2019-07-11 17:48 UTC, velddev commented
Make sure to remove `dist/` for this commit

2019-07-20 19:21 UTC, velddev reviewed
Check the changes here

2019-07-20 19:21 UTC, velddev commented on .env.schema
> +# postgress
postgres*

2019-07-20 19:21 UTC, velddev commented on .env.schema
> +DATABAE_DATABAE=
DATABASE :')

2019-07-20 19:21 UTC, velddev commented on src/routes/users.router.ts
> +function CalculateLevel(exp : number)
Make sure to keep consistent in style

2019-07-20 19:21 UTC, velddev commented on src/routes/users.router.ts
>          loadPNG(avatarUrl, (avatar) =>
maybe promisify loadPNG?

2019-07-20 20:00 UTC, Niputi commented on src/routes/users.router.ts
> +function CalculateLevel(exp : number)
:thinking: it's the original style

2019-07-20 20:43 UTC, velddev requested changes
code LGTM, some variables need to be synced now with spelling stuff

2019-07-20 20:43 UTC, velddev commented on .env.schema
> +DATABAE_USER=
Spelling issues

2019-07-20 20:43 UTC, velddev commented on .env.schema
> +DATABAE_PASSWORD=
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/index.d.ts
> +        DATABAE_PASSWORD: string,
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/index.d.ts
> +        DATABAE_USER: string,
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/index.d.ts
> +        DATABAE: string
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +    password: process.env.DATABAE_PASSWORD,
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +    database: process.env.DATABAE,
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +    host: process.env.DATABAE_HOST,
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +    user: process.env.DATABAE_USER,
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +    port: Number(process.env.DATABAE_PORT)
Spelling issues

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +function CalculateLevel(exp : number)
the original style is `exp: number`

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +Router().get('/api/custom', async (req, res) => {
consider using "

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +Router().get('/api/ship', async (req, res) => {
consider using "

2019-07-20 20:43 UTC, velddev commented on src/routes/users.router.ts
> +Router().get('/api/user', async (req, res) =>
consider using "

2019-07-20 20:48 UTC, Niputi commented on src/routes/users.router.ts
> +    password: process.env.DATABAE_PASSWORD,
ups

2019-07-26 15:17 UTC, merged